/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppErrorBoundary: typeof import('./../src/components/common/AppErrorBoundary.vue')['default']
    ChatComposer: typeof import('./../src/components/ai/ChatComposer.vue')['default']
    LoginForm: typeof import('./../src/components/auth/LoginForm.vue')['default']
    ProductCard: typeof import('./../src/components/shop/ProductCard.vue')['default']
    ProductEditor: typeof import('./../src/components/shop/ProductEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeMarkdown: typeof import('./../src/components/ai/SafeMarkdown.vue')['default']
    SvgIcon: typeof import('./../src/components/common/SvgIcon.vue')['default']
  }
}

// For TSX support
declare global {
  const AppErrorBoundary: (typeof import('./../src/components/common/AppErrorBoundary.vue'))['default'];
  const ChatComposer: (typeof import('./../src/components/ai/ChatComposer.vue'))['default'];
  const LoginForm: (typeof import('./../src/components/auth/LoginForm.vue'))['default'];
  const ProductCard: (typeof import('./../src/components/shop/ProductCard.vue'))['default'];
  const ProductEditor: (typeof import('./../src/components/shop/ProductEditor.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const SafeMarkdown: (typeof import('./../src/components/ai/SafeMarkdown.vue'))['default'];
  const SvgIcon: (typeof import('./../src/components/common/SvgIcon.vue'))['default'];
}
