// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TitleBar: typeof import('./../src/components/TitleBar/index.vue')['default'];
    VanButton: typeof import('vant/es')['Button'];
    VarButton: typeof import('@varlet/ui')['_ButtonComponent'];
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent'];
  }
}
