/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutForm: typeof import('@nutui/nutui')['Form']
    NutFormItem: typeof import('@nutui/nutui')['FormItem']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanNavBar: typeof import('vant/es')['NavBar']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}

// For TSX support
declare global {
  const NutAvatar: typeof import('@nutui/nutui')['Avatar']
  const NutButton: typeof import('@nutui/nutui')['Button']
  const NutCard: typeof import('@nutui/nutui')['Card']
  const NutCell: typeof import('@nutui/nutui')['Cell']
  const NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
  const NutForm: typeof import('@nutui/nutui')['Form']
  const NutFormItem: typeof import('@nutui/nutui')['FormItem']
  const NutGrid: typeof import('@nutui/nutui')['Grid']
  const NutGridItem: typeof import('@nutui/nutui')['GridItem']
  const NutInput: typeof import('@nutui/nutui')['Input']
  const NutSwiper: typeof import('@nutui/nutui')['Swiper']
  const NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
  const NutTabbar: typeof import('@nutui/nutui')['Tabbar']
  const NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const VanButton: typeof import('vant/es')['Button']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VarButton: typeof import('@varlet/ui')['_ButtonComponent']
  const VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
}