/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/examples/tasks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getTasks'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/examples/tasks/{id}/toggle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['toggleTask'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/examples/feed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getFeed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/examples/{scenario}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Development-only request error fixtures exposed by Mock and Gin. */
    get: operations['triggerRequestErrorExample'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listProjects'];
    put?: never;
    post: operations['createProject'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getProject'];
    put?: never;
    post?: never;
    delete: operations['deleteProject'];
    options?: never;
    head?: never;
    patch: operations['updateProject'];
    trace?: never;
  };
  '/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listProducts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listAdminProducts'];
    put?: never;
    post: operations['createProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteProduct'];
    options?: never;
    head?: never;
    patch: operations['updateProduct'];
    trace?: never;
  };
  '/ai/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['streamChat'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiResponse: {
      code: number;
      data: unknown;
      msg: string;
      requestId?: string;
    };
    LoginRequest: {
      name: string;
      password: string;
    };
    LoginResult: {
      name: string;
      token: string;
      expiresIn?: number;
    };
    UserProfile: {
      id: number;
      name: string;
      /** @enum {string} */
      role: 'admin' | 'member';
      /** @enum {string} */
      plan: 'free' | 'pro';
    };
    Task: {
      id: number;
      title: string;
      done: boolean;
    };
    FeedItem: {
      id: number;
      title: string;
      summary: string;
      category: string;
    };
    Project: {
      id: number;
      ownerId: number;
      name: string;
      description: string;
      status: components['schemas']['ProjectStatus'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    ProjectStatus: 'active' | 'paused' | 'archived';
    ProjectInput: {
      name: string;
      description?: string;
      status?: components['schemas']['ProjectStatus'];
    };
    ProjectUpdateInput: {
      name?: string;
      description?: string;
      status?: components['schemas']['ProjectStatus'];
    };
    ProjectPage: {
      list: components['schemas']['Project'][];
      total: number;
      page: number;
      pageSize: number;
      hasMore: boolean;
    };
    Product: {
      id: number;
      sku: string;
      name: components['schemas']['LocalizedText'];
      subtitle: components['schemas']['LocalizedText'];
      description: components['schemas']['LocalizedText'];
      category: string;
      brand: string;
      coverUrl: string;
      /** Format: int64 */
      priceCents: number;
      /** Format: int64 */
      originalPriceCents: number;
      stock: number;
      sales: number;
      /** Format: double */
      rating: number;
      status: components['schemas']['ProductStatus'];
      featured: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    ProductStatus: 'draft' | 'on_sale' | 'sold_out';
    LocalizedText: {
      'zh-CN': string;
      'en-US': string;
      'ja-JP': string;
    };
    ProductInput: {
      sku: string;
      name: components['schemas']['LocalizedText'];
      subtitle: components['schemas']['LocalizedText'];
      description: components['schemas']['LocalizedText'];
      category: string;
      brand: string;
      coverUrl: string;
      priceCents: number;
      originalPriceCents: number;
      stock: number;
      sales: number;
      rating: number;
      status: components['schemas']['ProductStatus'];
      featured: boolean;
    };
    ProductUpdateInput: {
      sku?: string;
      name?: components['schemas']['LocalizedText'];
      subtitle?: components['schemas']['LocalizedText'];
      description?: components['schemas']['LocalizedText'];
      category?: string;
      brand?: string;
      coverUrl?: string;
      priceCents?: number;
      originalPriceCents?: number;
      stock?: number;
      sales?: number;
      rating?: number;
      status?: components['schemas']['ProductStatus'];
      featured?: boolean;
    };
    ProductPage: {
      list: components['schemas']['Product'][];
      total: number;
      page: number;
      pageSize: number;
      hasMore: boolean;
    };
    DeleteResult: {
      deleted: boolean;
      id: number;
    };
    ChatMessage: {
      /** @enum {string} */
      role: 'system' | 'user' | 'assistant';
      content: string;
    };
    ChatRequest: {
      conversationId?: string;
      messages: components['schemas']['ChatMessage'][];
    };
  };
  responses: never;
  parameters: {
    Page: number;
    PageSize: number;
    ProjectId: number;
    ProductId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Login result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['LoginResult'];
          };
        };
      };
    };
  };
  getUserProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['UserProfile'];
          };
        };
      };
    };
  };
  getTasks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['Task'][];
          };
        };
      };
    };
  };
  toggleTask: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Updated task */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['Task'];
          };
        };
      };
    };
  };
  getFeed: {
    parameters: {
      query?: {
        cursor?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cursor feed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  triggerRequestErrorExample: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario:
          | 'bad-request'
          | 'unauthorized'
          | 'forbidden'
          | 'not-found'
          | 'conflict'
          | 'validation'
          | 'server-error'
          | 'timeout';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Business validation or delayed success fixture */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Bad request fixture */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized fixture */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden fixture */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found fixture */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflict fixture */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Server error fixture */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listProjects: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated projects owned by the current user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['ProjectPage'];
          };
        };
      };
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectInput'];
      };
    };
    responses: {
      /** @description Created project */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['Project'];
          };
        };
      };
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ProjectId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ProjectId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deletion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ProjectId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectUpdateInput'];
      };
    };
    responses: {
      /** @description Updated project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  listProducts: {
    parameters: {
      query?: {
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
        keyword?: string;
        category?: string;
        sort?: 'featured' | 'sales' | 'price_asc' | 'price_desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public on-sale product catalog */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['ProductPage'];
          };
        };
      };
    };
  };
  getProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public product detail */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['Product'];
          };
        };
      };
    };
  };
  listAdminProducts: {
    parameters: {
      query?: {
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
        keyword?: string;
        status?: components['schemas']['ProductStatus'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Product management list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'] & {
            data?: components['schemas']['ProductPage'];
          };
        };
      };
    };
  };
  createProduct: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductInput'];
      };
    };
    responses: {
      /** @description Created product */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  deleteProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Soft-deleted product */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  updateProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdateInput'];
      };
    };
    responses: {
      /** @description Updated product */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
    };
  };
  streamChat: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest'];
      };
    };
    responses: {
      /** @description Server-sent ChatChunk events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
    };
  };
}
